In [ ]:
# Baics of Tensorflow

In [1]:
# importing
import tensorflow as tf
print(tf.__version__)

2.18.0


In [2]:
# creating tensors
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# number of dimensions of a tensor
scalar.ndim

0

In [4]:
# a vector constant
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [7]:
# a matrix constant
matrix = tf.constant([[10,7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [10]:
# create another matrix
matrix_with_d = tf.constant([
    [3., 4.],
    [6., 7.]
], dtype=tf.float16)
matrix_with_d

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[3., 4.],
       [6., 7.]], dtype=float16)>

In [11]:
matrix_with_d.ndim

2

In [12]:
# new tensor
new_tensor = tf.constant([[[0 for _ in range(4)] for _ in range(3)] for _ in range(2)])
new_tensor

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)>

In [13]:
new_tensor.ndim

3

In [14]:
# using tf.Variable
tf.Variable

tensorflow.python.ops.variables.Variable

In [15]:
vartensor = tf.Variable([10,7])
consttensor = tf.constant([10,7])
vartensor, consttensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [16]:
# attempt changing
vartensor[0] = 1
consttensor[0] = 1

TypeError: 'ResourceVariable' object does not support item assignment

In [17]:
vartensor[0].assign(1)
consttensor[0].assign(1)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [23]:
# random tensors
random_tensor = tf.random.Generator.from_seed(42)
random_tensor = random_tensor.normal(shape=(3,2))
random_tensor2 = tf.random.Generator.from_seed(42)
random_tensor2 = random_tensor2.normal(shape=(3,2))
random_tensor, random_tensor2, random_tensor==random_tensor2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [26]:
# shuffle values
mytensor = tf.constant([[10,7],[3,4],[2,5]])
tf.random.shuffle(mytensor, seed=3)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [29]:
# create a new tensor
tf.ones([10,7]), tf.zeros([10,7])

(<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
 array([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(10, 7), dtype=float32, numpy=
 array([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>)

In [34]:
# Numpy arr to tensor
import numpy as np

numpy_A = np.arange(1,25, dtype=np.int32)
A=tf.constant(numpy_A, shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [36]:
# attributes
print(A.ndim)
print(A.shape)
print(tf.size(A))
print(A.dtype)

3
(2, 3, 4)
tf.Tensor(24, shape=(), dtype=int32)
<dtype: 'int32'>


In [38]:
# manipulation
t1 = tf.constant([[1,2], [2,3]])
t2 = tf.constant([[4,2], [9,1]])

print(t1+t2)
print(t1-t2)
print(t1*t2)
print(t1/t2)
print(t1+10)

tf.Tensor(
[[ 5  4]
 [11  4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-3  0]
 [-7  2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 4  4]
 [18  3]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0.25       1.        ]
 [0.22222222 3.        ]], shape=(2, 2), dtype=float64)
tf.Tensor(
[[11 12]
 [12 13]], shape=(2, 2), dtype=int32)


In [40]:
# Matrix Multiplication
tf.matmul(t1, t2), t1*t2

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[22,  4],
        [35,  7]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 4,  4],
        [18,  3]], dtype=int32)>)

In [42]:
# reshaping
t = tf.constant([[1,2,3], [4,5,6],[7,8,9]])
tf.reshape(t, [9,1])

<tf.Tensor: shape=(9, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]], dtype=int32)>

In [43]:
# transpose
tf.transpose(t)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]], dtype=int32)>